### PR TITLE
Fix #43 - restricted setuptols version for py3.2

### LINKED ISSUE #43: Check if travis works with newly released setuptools
On 3.12.2016 setuptools 30.0.0 were relased. Support for python 3.2 is dropped.

@ant6 can you take a look ?

### PR DESCRIPTION
**Pull request by ant6**
@grzanka done

### CODE REVIEW

**Comment by grzanka** [comment]
Check this one: https://github.com/DataMedSci/pymchelper/pull/97

**Comment by ant6** [comment]
Oh, I see...

**Comment by ant6** [comment]
@grzanka but why did pep8s fail?

**Comment by grzanka** [comment]
@ant6 in the meantime flake8 package got a new version with more restrictive policy (to be checked, but this is my feeling)

**Comment by ant6** [comment]
@grzanka should I add py3.6 and 3.6 dev to *allow failure*? Weird thing is py3.6 errored but 3.6dev passed...

**Comment by grzanka** [comment]
Add 3.6 to "allow failures", 3.6-dev should work, see:
https://travis-ci.org/DataMedSci/pymchelper/builds/180990904

**Comment by grzanka** [comment]
Things will change soon, see https://www.python.org/dev/peps/pep-0494/#schedule

**Comment by grzanka** [comment]
@ant6 can you fix pep8 issues ?

**Comment by ant6** [comment]
@grzanka yes, sure

**Comment by ant6** [comment]
Done :)

**Pull request merged**
