### PR TITLE
old package requirements set for python3.3 as it looks that support

### LINKED ISSUE #97: travis job fails due to argparse.ArgumentError
See i.e. https://travis-ci.org/DataMedSci/mcpartools/jobs/311525863
and https://github.com/DataMedSci/pymchelper/issues/278

### PR DESCRIPTION
**Pull request by grzanka**
for python3.3 is getting poorer and poorer
Fixes #97

### CODE REVIEW

**Comment by ant6** [comment]
Maybe we should consider dropping support for 3.3? Is it still in use somewhere in popular linux distros?

**Comment by grzanka** [comment]
You are right - it seems it has reached end of support:
https://www.python.org/dev/peps/pep-0398/

I'd merge this PR (if successful) and create another issue for dropping 3.3

3.2 I'd like to keep - it is used in Debian 7.

**Comment by ant6** [comment]
Ok 👍

**Comment by grzanka** [comment]
@ant6 also - please review this one

**Pull request merged**
