### PR TITLE
Feature/pyinstaller

### PR DESCRIPTION
**Pull request by grzanka**
Attempt to solve #27 using pyinstaller

### CODE REVIEW

**Comment by ant6** [comment]
@grzanka what is the main idea behind this? Windows edition done with pyinstaller? If so how can I build it and test by myself on Windows?

**Comment by grzanka** [comment]
@ant6 The idea is to produce single binary executable file (mcpartools + python libraries inside) for Linux users without root access and without python installed.
Something more fancy than pyz files available here: https://github.com/DataMedSci/mcpartools/releases/tag/v0.1.6 and generated with nuitka via https://github.com/DataMedSci/mcpartools/blob/master/make_single_executable.sh

The idea is also to automatically deploy to github releases (i.e. here https://github.com/DataMedSci/mcpartools/releases/tag/v0.1.6 under Downloads) automatically after "Draft release" button is pushed here: https://github.com/DataMedSci/mcpartools/releases

**Comment by grzanka** [comment]
Previously I had idea to produce such files with nuitka, but it seems that pyinstaller makes a reasonable size binary (~10MB)

**Comment by grzanka** [comment]
I will undo your merge, as `squash merge` should be made, not a normal merge

**Comment by ant6** [comment]
Oh, sorry :(

**Pull request merged**
